# Generated by Django 4.2 on 2023-04-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=10, max_digits=30)),
                ('market_cap', models.DecimalField(decimal_places=10, max_digits=30)),
                ('volume_24h', models.DecimalField(decimal_places=10, max_digits=30)),
                ('percent_change_24h', models.DecimalField(decimal_places=2, max_digits=30)),
            ],
        ),
    ]
